### ISSUE TITLE
This is technically not a _dynamic_ import. Consider Readme update.

### ISSUE THREAD

**Issue by TheLarkInn** [airbnb/babel-plugin-dynamic-import-webpack#2]
Not to squabble over semantics, but a conversion from `import()` to `require.ensure()` is really not a dynamic import statement through webpack. 

I've already started to see people saying that its possible to perform dynamic imports when that really is 0% supported by webpack (since it is only accomplished through static analysis). Since you folks are pretty well regarded in the OSS technology you publish, I just want to ensure that our webpack user base doesn't have misguided expectations about what is possible.

With that in mind, would you consider renaming this module to be `whatwg-import-webpack` instead of `dynamic-import-webpack`? 

Thanks for providing this awesome workaround to the API. You can track our github issue for implementing the native webpack support for `import()` as we may add additional require.ensure features. (https://github.com/webpack/webpack/issues/3098). (It will however, still be statically analyzed). 

Actually as I've been writing this I also noticed that @domenic called the proposal `[dynamic-loader]` so that is fair that you would call it there. 

I would be happy to PR the README to state that this doesn't really perform _truly_ dynamic imports, since webpack doesn't support this.

**Comment by TheLarkInn** [comment]
Oh and PS: Nice work on this!!! If @hzoo or we (@webpack) can ever help, just let us know. :-D

**Comment by ljharb** [comment]
The `import()` syntax is named "dynamic import" - it would be inappropriate to use any other name, and "whatwg-import" would make no sense since WhatWG has nothing to do with this ECMA language proposal.

It's a good point that it won't actually be dynamic - in the sense that it will only work with a static hardcoded string. However, importing or requiring from a non-hardcoded-path is a bad practice anyways, so I suspect very few will run into the problem. A PR to the readme that clarifies this is welcome!

**Comment by domenic** [comment]
> However, importing or requiring from a non-hardcoded-path is a bad practice anyways, so I suspect very few will run into the problem.

Ummmm the entire point of `import()` is to allow that. If you're not doing dynamic import, you're better off just using normal import statements.

**Comment by ljharb** [comment]
@domenic not when you want to defer loading of the asset until later.

**Comment by ljharb** [comment]
Specifically, `import()` allows deferred loading, and conditional loading, neither of which require using a dynamic path - and the common best practice when deferring or conditionally loading things is still to use a hardcoded static string for the path.

**Comment by domenic** [comment]
Fair enough. But I don't think we should be calling the other large use case for import() bad practice.

**Comment by ljharb** [comment]
Oh certainly that shouldn't go in the readme - but the majority of the community in my experience already calls it that, and uses linter rules to ensure it doesn't happen, so that's kind of defacto reality at this point :-)

**Comment by TheLarkInn** [comment]
I totally agree as you could see my digression in the initial comment. My point is if we can any way make clear that using this for webpack doesnt result into a truly dynamic module load, then let's do so. Less confusion => better dev exp

**Comment by TheLarkInn** [comment]
Awesome awesome I'll get a PR in!!
