### ISSUE TITLE
Default export is not picked up properly

### ISSUE THREAD

**Issue by kirill-konshin** [airbnb/babel-plugin-dynamic-import-webpack#24]
I have the following Babel config:

```json
{
  "presets": [
    "react-app"
  ],
  "plugins": [
    "dynamic-import-webpack",
    "transform-decorators-legacy"
  ]
}
```

I am also using Webpack 2.

In order to make everything work with this setup I have to do some custom stuff in React Router configuration:

```js
<Route path='/' getComponent={() => import('../path/to/component').then(cmp => cmp.default)}/>
```

Without `.then(cmp => cmp.default)` it does not work.

**Comment by ljharb** [comment]
That's per spec. `import()` returns a promise for a ModuleRecord.

**Comment by kirill-konshin** [comment]
My bad. But it's interesting, in my other project I have exactly the same construction that works:

```js
<Route path='/' getComponent={() => import('../path/to/component')}/>
```

It works w/o explicit default... Maybe something it is different React Router version or different Babel presets/plugins. Or maybe it's because that project uses Webpack 1 (where it works somehow) and this project uses Webpack 2.

**Comment by ljharb** [comment]
I'm not sure why that works somewhere else - this repo is for webpack 1; webpack 2 supports `import()` natively. If the `.default` isn't required in webpack 2, I'd file that as a bug for them - as this transform shouldn't be used for webpack 2.

**Comment by kirill-konshin** [comment]
That's true, I swapped `dynamic-import-webpack` with `syntax-dynamic-import`. The behavior is the same for Webpack 2, `.then(cmp => cmp.default)` is needed.

Although in Webpack 1 and `dynamic-import-webpack`, as I said, it's not required for some reason. I'll investigate more.

**Comment by ljharb** [comment]
If that's the case, that's indeed a bug with this module.

**Comment by ljharb** [comment]
Can you share the code that's exporting the component?

**Comment by kirill-konshin** [comment]
Nothing special, `export default class Foo extends React.Component {...}` and that's the only export.

**Comment by ljharb** [comment]
And if you `require()` that file directly, do you need `.default` to get to the component?

**Comment by kirill-konshin** [comment]
```js
getComponent: () => {
    return new Promise((res) => {
        require.ensure([], () => {
            res(require('../components/layout'));
        });
    });
},
```

No `.default` needed.

Here's the set of Babel presets/plugins used:

```json
{
  "presets": [
    ["es2015", {"loose": true}],
    "stage-0",
    "react"
  ],
  "plugins": [
    "add-module-exports",
    "transform-decorators-legacy",
    "transform-proto-to-assign",
    "transform-class-properties",
    "dynamic-import-webpack"
  ],
}
```

It appears that it's `add-module-exports` that is causing the issue, if removed, then `.default` becomes needed. But, when used with Webpack 2 it does not make any difference...

**Comment by ljharb** [comment]
Right - so that's because webpack 2 doesn't use your babel module settings, so it ignores add-module-exports.

So to recap: this isn't a bug with this module, it's just a difference with how you transpile `export default`.

**Comment by kirill-konshin** [comment]
Right. Thank you :)
