### ISSUE TITLE
Avoid the dependency on both the syntax plugin and this one

### ISSUE THREAD

**Issue by loganfsmyth** [airbnb/babel-plugin-dynamic-import-webpack#4]
Most of Babel's transformation plugins internally depend on their syntax plugins so people don't have to list both, e.g. https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-class-properties/src/index.js#L24

Seems like that could benefit this plugin too.

**Comment by ljharb** [comment]
awesome, that sounds great
