### ISSUE TITLE
1.0.2 breaks code splitting

### ISSUE THREAD

**Issue by tomatau** [airbnb/babel-plugin-dynamic-import-webpack#42]
Updating from "^1.0.1" to "^1.0.2" has broken my code splitting. This shouldn't be a breaking change from a patch update.

```js
{
  test: /\.jsx?$/,
  include: [ APP, CONFIG, SERVER ],
  loader: 'babel-loader',
  options: {
    presets: [
      [ 'env', {
        targets: { browsers: [ 'last 2 versions' ] },
        modules: false,
      } ],
      'react',
    ],
    plugins: [
      'dynamic-import-webpack',
      'transform-export-extensions',
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-object-rest-spread',
      'add-module-exports',
      'lodash',
      'ramda',
      'react-require',
      [ 'provide-modules', {
        'debug': 'debug',
      } ],
      'babel-root-import',
    ],
  },
}
```

Also possibly worth note is:

```
  resolve: {
    modules: [ SRC, STYLES, 'node_modules' ],
    extensions: [
      '.js', '.jsx', '.scss',
    ],
  },
```

And using `react-loadable/webpack`

**Comment by ljharb** [comment]
Can you elaborate on what you mean by "broken your code splitting"? What's no longer working?

**Comment by ljharb** [comment]
Ah - I see you're using `modules: false` - in that case, why would you use this plugin at all? Its sole purpose is to transform `import()`, but webpack handles that for you when the modules transform is disabled.

**Comment by tomatau** [comment]
I feel like your conclusion is wrong. if I remove the webpack plugin, webpack doesn't bundle code splits, if I include it, it does... 

I'm on webpack 3 and this plugin transforms the `import()` which webpack doesn't understand into a `require.ensure([]` which webpack then can handle.

> Can you elaborate on what you mean by "broken your code splitting"? What's no longer working?

Urm, not sure how much more to elaborate?

using v1.0.1 this is the development webpack bundle output:
```
                        Asset       Size  Chunks                    Chunk Names
    0.29ccbdff3a6c145902f8.js    21.2 kB       0  [emitted]
    1.29ccbdff3a6c145902f8.js    5.08 kB       1  [emitted]
    2.29ccbdff3a6c145902f8.js    5.88 kB       2  [emitted]
    3.29ccbdff3a6c145902f8.js    7.31 kB       3  [emitted]
 body.29ccbdff3a6c145902f8.js    4.91 MB       4  [emitted]  [big]  body
 head.29ccbdff3a6c145902f8.js     297 kB       5  [emitted]  [big]  head
body.29ccbdff3a6c145902f8.css  293 bytes       4  [emitted]         body
```

production:
```
                        Asset       Size  Chunks                    Chunk Names
    0.f31a2890dc1395a2f2dc.js    2.77 kB       0  [emitted]
    1.f31a2890dc1395a2f2dc.js    1.38 kB       1  [emitted]
    2.f31a2890dc1395a2f2dc.js     1.5 kB       2  [emitted]
    3.f31a2890dc1395a2f2dc.js    2.05 kB       3  [emitted]
 body.f31a2890dc1395a2f2dc.js     467 kB       4  [emitted]  [big]  body
 head.f31a2890dc1395a2f2dc.js    9.33 kB       5  [emitted]         head
body.f31a2890dc1395a2f2dc.css  816 bytes       4  [emitted]         body
```
---
if I upgrade to 1.0.2, the development bundle output becomes:
```
                        Asset       Size  Chunks                    Chunk Names
 body.40862c82a443c18317c4.js    4.92 MB       0  [emitted]  [big]  body
 head.40862c82a443c18317c4.js     295 kB       1  [emitted]  [big]  head
body.40862c82a443c18317c4.css  293 bytes       0  [emitted]         body
```

The production build breaks
```
ERROR in body.fd7974f3a71d9180c03e.js from UglifyJs
Unexpected character '`' [body.fd7974f3a71d9180c03e.js:34144,8]
```

**Comment by ljharb** [comment]
Thanks for the additional information. I believe in Webpack 2+, it has native support for `import()` - this plugin should only be needed on webpack 1.

@kesne, can you clarify, in case I'm incorrect?

**Comment by tomatau** [comment]
@ljharb I'm literally removing the plugin from the webpack config's babel-loader options and you can see the output difference. The plugin makes it work in 1.0.1. Removing the plugin and the import() statements have no affect.

**Comment by kesne** [comment]
This plugin is designed for usage in Webpack 1 and 2. For webpack 3 you should use the webpack-native bundle splitting.

**Comment by tomatau** [comment]
The native bundle splitting should "just work" https://webpack.js.org/guides/code-splitting/#dynamic-imports but it doesn't, the plugin fixes it for me... (1.0.1)

edit: I'll try the syntax dynamic import plugin to see if this also solves the problem and update.
edit: no luck, doesn't solve anything

**Comment by ljharb** [comment]
Did you include the webpack chunk name? (can you share the code that's using `import()`?)

**Comment by tomatau** [comment]
No I'm not using the * webpackChunkName: "foo" */ as it's an optional enhancement.

I'm using a library called https://github.com/jamiebuilds/react-loadable

e.g.
```js
const LoadableHomeRoute = Loadable({
  loader: () => import('../../routes/HomeRoute/HomeRoute'),
  loading: Loading,
  webpack: () => [ require.resolveWeak('../../routes/HomeRoute/HomeRoute') ],
  modules: [ '../../routes/HomeRoute/HomeRoute' ],
})
```

**Comment by loganfsmyth** [comment]
It might help to see the full error that you get when this plugin is left out. To me it very much seems like you're using Babel and thus need `babel-plugin-syntax-dynamic-import`. While Webpack may support `import()` natively, you still need that plugin so that Babel itself doesn't throw about the experimental syntax.

**Comment by tomatau** [comment]
@loganfsmyth there aren't any errors when left out in development. The problem is that the code split chunks aren't being created and so only the normal chunks are created without errors.

edit: also see my edits for https://github.com/airbnb/babel-plugin-dynamic-import-webpack/issues/42#issuecomment-375813672 I tried the syntax plugin to no avail :(

**Comment by tomatau** [comment]
I think I've found the problem. Babel is merging configs so a server side render that uses `"dynamic-import-node"` in a .babelrc is being merged into the webpack loader config.... :|

edit:

Thanks for the help everyone :) 👍
