### ISSUE TITLE
Node polyfill

### ISSUE THREAD

**Issue by DylanPiercey** [airbnb/babel-plugin-dynamic-import-webpack#7]
Hey all, I made a proper node polyfill for require.ensure - would be cool if this library could somehow automatically import it.

Heres a link if you are interested -
https://github.com/DylanPiercey/require-ensure

Feel free to close the issue or let me know if I can be of help in anyway.

**Comment by ljharb** [comment]
Thanks, very interesting!

We're working on a separate babel plugin for this syntax for node, and we wouldn't want to mutate the global `require` in node so that `require.ensure` actually worked at runtime. I'll close this but feel free to discuss here further!

**Comment by DylanPiercey** [comment]
Ah thats cool, well then you might enjoy https://github.com/DylanPiercey/require-load which does just that. Also works seamlessly with nodes require.

**Comment by loganfsmyth** [comment]
Note, that module is also not just mutating `require` at https://github.com/DylanPiercey/require-ensure/blob/master/src/index.js#L7. `Object.getPrototypeOf(require) === Function.prototype`, so you're adding a `.ensure` and `.include` to every function's prototype chain.

**Comment by DylanPiercey** [comment]
@loganfsmyth that is correct. I did that in order to avoid having to include it at the top of every file.

If it was something you guys were interested in I could make it a 'per require' patch and expose the global polyfill as `require-ensure/polyfill` or similar.

At any rate I am interested in helping if needed / promoting the idea of making this transform isomorphic :).
